services:

  postgres:
    image: postgres:15
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Johan123
      POSTGRES_DB: mini_proyect
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_runner
    depends_on:
      - postgres
    volumes:
      - ./:/liquibase/changelog
      - ./postgresql-42.7.9.jar:/liquibase/lib/postgresql.jar
    working_dir: /liquibase/changelog
    command:
      --url=jdbc:postgresql://postgres:5432/mini_proyect
      --username=postgres
      --password=Johan123
      --driver=org.postgresql.Driver
      --changeLogFile=changelog-master.yaml
      update

volumes:
  postgres_data: